language: node_js
node_js:
  - 12
before_install:
  - ignore
before_script:
  - ignore

env:
  global:
    - TARGET_JDI_LIGHT_BRANCH=gh-pages

stages:
  - test
  - merge

jobs:
  include:
    - stage: test
      name: Run tests
      script:
        - echo "Test stage goes here, right now tests are considered passed by default"

    - stage: merge
      name: Merge the changes into jdi-light repo
      if: branch = "travis-setup"
      script:
        - sudo snap install hub --classic
        - hub version
        - sh travis_automerge_to_jdi_light.sh
after_failure:
  - echo "Build has failed"
after_script:
  - ignore
after_success:
  - echo "Build has succeeded"
