language: node_js
node_js:
  - 12
before_install:
  # Before_install section
  - ignore
before_script:
  # Before_script section
  - ignore

env:
  global:
    - SOURCE_TEST_SITE_BRANCH=travis-setup
    - TARGET_JDI_LIGHT_BRANCH=gh-pages

stages:
  - prepare
  - compile
  - test
  - merge

jobs:
  include:
    - stage: prepare
      name: Prepare
      script:
        - npm --version

    - stage: compile
      name: Compile
      script:
        - echo "Compile stage"

    - stage: test
      name: Run tests
      script:
        - echo "Test stage goes here, right now tests are considered passed by default"

    - stage: merge
      name: Merge the changes into jdi-light repo
      if: branch = "travis-setup"
      script:
        - sh travis_automerge_to_jdi_light_ssh.sh
after_failure:
  - echo "Build has failed"
after_script:
  #One can add some cleanup here
  - ignore
after_success:
  - echo "Build has succeeded"